In [133]:
#import all libraries needed 
import os
import pandas as pd

# from api_keys import gkey
import gmaps
import gmaps.datasets
import matplotlib.pyplot as plt
import numpy as np
import requests
import time
from scipy.stats import linregress
import scipy.stats as st
from sqlalchemy import create_engine

In [134]:
#Get Path to get to the Datasets
WorldBankpath = os.path.join('Data Sets', 'WorldBank.csv')

In [135]:
#read the files 
WorldBank = pd.read_csv(WorldBankpath)

In [136]:
WorldBank.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1990 [YR1990]', '2000 [YR2000]', '2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]'],
      dtype='object')

In [137]:
WorldBankDrop = WorldBank[['Country Name', 'Country Code', 'Series Name','2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]']]

In [138]:
WorldBankDrop

,Country Name,Country Code,Series Name,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,Latin America & Caribbean,LCN,"Population, total",596538911,603097381,609600087,616002686,622301089,628484873,634545282,640454810
1,Latin America & Caribbean,LCN,Population growth (annual %),1.1198476558079,1.09942031928911,1.07821824548762,1.0502949616541,1.02246356114104,0.993696477365475,0.964288761807637,0.931301227451243
2,Latin America & Caribbean,LCN,Surface area (sq. km),20425484.4078087,20425482.3765587,20425483.3921837,20425483.3921837,20425483.3921837,20426078.3765625,20426078.3765625,20425545.9765625
3,Latin America & Caribbean,LCN,Population density (people per sq. km of land ...,29.7641321747825,30.0919866753081,30.4198271919214,30.7396318936835,31.0539334286253,31.362515271189,31.6649404813693,31.9606855829336
4,Latin America & Caribbean,LCN,Poverty headcount ratio at national poverty li...,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...
275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Last Updated: 09/16/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
WorldBank['Country Code'].value_counts()

CRI    55
NIC    55
SLV    55
LCN    55
HND    55
Name: Country Code, dtype: int64

In [140]:
# Remove the rows with missing data
cleanBlank = WorldBankDrop.dropna(how="any")
cleanBlank.count()

Country Name     275
Country Code     275
Series Name      275
2011 [YR2011]    275
2012 [YR2012]    275
2013 [YR2013]    275
2014 [YR2014]    275
2015 [YR2015]    275
2016 [YR2016]    275
2017 [YR2017]    275
2018 [YR2018]    275
dtype: int64

In [141]:
cleanBlank

,Country Name,Country Code,Series Name,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
0,Latin America & Caribbean,LCN,"Population, total",596538911,603097381,609600087,616002686,622301089,628484873,634545282,640454810
1,Latin America & Caribbean,LCN,Population growth (annual %),1.1198476558079,1.09942031928911,1.07821824548762,1.0502949616541,1.02246356114104,0.993696477365475,0.964288761807637,0.931301227451243
2,Latin America & Caribbean,LCN,Surface area (sq. km),20425484.4078087,20425482.3765587,20425483.3921837,20425483.3921837,20425483.3921837,20426078.3765625,20426078.3765625,20425545.9765625
3,Latin America & Caribbean,LCN,Population density (people per sq. km of land ...,29.7641321747825,30.0919866753081,30.4198271919214,30.7396318936835,31.0539334286253,31.362515271189,31.6649404813693,31.9606855829336
4,Latin America & Caribbean,LCN,Poverty headcount ratio at national poverty li...,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...
270,Nicaragua,NIC,"Total debt service (% of exports of goods, ser...",16.5034812629961,13.1993935702772,12.619058858323,13.0433478797368,15.4249727683352,15.9334779279193,19.8201596232055,19.0280490011247
271,Nicaragua,NIC,Net migration,..,-135020,..,..,..,..,-106360,..
272,Nicaragua,NIC,"Personal remittances, received (current US$)",913600000,1016300000,1081300000,1140200000,1197500000,1268100000,1394700000,1504800000
273,Nicaragua,NIC,"Foreign direct investment, net inflows (BoP, c...",936300000,767700000,815500000,884100000,949900000,898700000,771900000,359200000
274,Nicaragua,NIC,Net official development assistance and offici...,536580017.089844,532320007.324219,495799987.792969,432170013.427734,457920013.427734,430980010.986328,562590026.855469,351950012.207031

In [142]:
cleanBlank2 = cleanBlank.drop(cleanBlank[(cleanBlank['Country Code'] == 'LCN')].index)

In [143]:
cleanBlank2

,Country Name,Country Code,Series Name,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018]
55,Costa Rica,CRI,"Population, total",4633086,4688000,4742107,4795396,4847804,4899345,4949954,4999441
56,Costa Rica,CRI,Population growth (annual %),1.20968236400613,1.17828835259712,1.14754994327846,1.11747392449788,1.08695279543583,1.05757038052655,1.02767608960277,0.99478225758881
57,Costa Rica,CRI,Surface area (sq. km),51100,51100,51100,51100,51100,51100,51100,51100
58,Costa Rica,CRI,Population density (people per sq. km of land ...,90.7380728554642,91.8135526831179,92.8732275754015,93.9168820994908,94.9432824128476,95.9527027027027,96.9438699569134,97.9130630630631
59,Costa Rica,CRI,Poverty headcount ratio at national poverty li...,21.7,20.6,20.7,22.4,21.7,20.5,20,21.1
...,...,...,...,...,...,...,...,...,...,...,...
270,Nicaragua,NIC,"Total debt service (% of exports of goods, ser...",16.5034812629961,13.1993935702772,12.619058858323,13.0433478797368,15.4249727683352,15.9334779279193,19.8201596232055,19.0280490011247
271,Nicaragua,NIC,Net migration,..,-135020,..,..,..,..,-106360,..
272,Nicaragua,NIC,"Personal remittances, received (current US$)",913600000,1016300000,1081300000,1140200000,1197500000,1268100000,1394700000,1504800000
273,Nicaragua,NIC,"Foreign direct investment, net inflows (BoP, c...",936300000,767700000,815500000,884100000,949900000,898700000,771900000,359200000
274,Nicaragua,NIC,Net official development assistance and offici...,536580017.089844,532320007.324219,495799987.792969,432170013.427734,457920013.427734,430980010.986328,562590026.855469,351950012.207031

In [144]:
cleanBlank2.columns

Index(['Country Name', 'Country Code', 'Series Name', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]'],
      dtype='object')

In [145]:
BankRename = cleanBlank2.rename(columns={'Country Name': 'country_name', 'Country Code' : 'country_code', 'Series Name': 'series_name','2011 [YR2011]': 'yr2011', '2012 [YR2012]': 'yr2012', '2013 [YR2013]': 'yr2013', '2014 [YR2014]' : 'yr2014', '2015 [YR2015]' : 'yr2015', '2016 [YR2016]' : 'yr2016', '2017 [YR2017]' : 'yr2017', '2018 [YR2018]' : 'yr2018'  })

In [146]:
BankRename

,country_name,country_code,series_name,yr2011,yr2012,yr2013,yr2014,yr2015,yr2016,yr2017,yr2018
55,Costa Rica,CRI,"Population, total",4633086,4688000,4742107,4795396,4847804,4899345,4949954,4999441
56,Costa Rica,CRI,Population growth (annual %),1.20968236400613,1.17828835259712,1.14754994327846,1.11747392449788,1.08695279543583,1.05757038052655,1.02767608960277,0.99478225758881
57,Costa Rica,CRI,Surface area (sq. km),51100,51100,51100,51100,51100,51100,51100,51100
58,Costa Rica,CRI,Population density (people per sq. km of land ...,90.7380728554642,91.8135526831179,92.8732275754015,93.9168820994908,94.9432824128476,95.9527027027027,96.9438699569134,97.9130630630631
59,Costa Rica,CRI,Poverty headcount ratio at national poverty li...,21.7,20.6,20.7,22.4,21.7,20.5,20,21.1
...,...,...,...,...,...,...,...,...,...,...,...
270,Nicaragua,NIC,"Total debt service (% of exports of goods, ser...",16.5034812629961,13.1993935702772,12.619058858323,13.0433478797368,15.4249727683352,15.9334779279193,19.8201596232055,19.0280490011247
271,Nicaragua,NIC,Net migration,..,-135020,..,..,..,..,-106360,..
272,Nicaragua,NIC,"Personal remittances, received (current US$)",913600000,1016300000,1081300000,1140200000,1197500000,1268100000,1394700000,1504800000
273,Nicaragua,NIC,"Foreign direct investment, net inflows (BoP, c...",936300000,767700000,815500000,884100000,949900000,898700000,771900000,359200000
274,Nicaragua,NIC,Net official development assistance and offici...,536580017.089844,532320007.324219,495799987.792969,432170013.427734,457920013.427734,430980010.986328,562590026.855469,351950012.207031

In [147]:
BankRename['country_name'].value_counts()

Honduras       55
Costa Rica     55
Nicaragua      55
El Salvador    55
Name: country_name, dtype: int64

In [148]:
BankRename.columns

Index(['country_name', 'country_code', 'series_name', 'yr2011', 'yr2012',
       'yr2013', 'yr2014', 'yr2015', 'yr2016', 'yr2017', 'yr2018'],
      dtype='object')

In [149]:
BankRename2 = BankRename[['country_name', 'series_name', 'yr2011', 'yr2012', 'yr2013',
       'yr2014', 'yr2015', 'yr2016', 'yr2017', 'yr2018']]

In [150]:
BankRename2

,country_name,series_name,yr2011,yr2012,yr2013,yr2014,yr2015,yr2016,yr2017,yr2018
55,Costa Rica,"Population, total",4633086,4688000,4742107,4795396,4847804,4899345,4949954,4999441
56,Costa Rica,Population growth (annual %),1.20968236400613,1.17828835259712,1.14754994327846,1.11747392449788,1.08695279543583,1.05757038052655,1.02767608960277,0.99478225758881
57,Costa Rica,Surface area (sq. km),51100,51100,51100,51100,51100,51100,51100,51100
58,Costa Rica,Population density (people per sq. km of land ...,90.7380728554642,91.8135526831179,92.8732275754015,93.9168820994908,94.9432824128476,95.9527027027027,96.9438699569134,97.9130630630631
59,Costa Rica,Poverty headcount ratio at national poverty li...,21.7,20.6,20.7,22.4,21.7,20.5,20,21.1
...,...,...,...,...,...,...,...,...,...,...
270,Nicaragua,"Total debt service (% of exports of goods, ser...",16.5034812629961,13.1993935702772,12.619058858323,13.0433478797368,15.4249727683352,15.9334779279193,19.8201596232055,19.0280490011247
271,Nicaragua,Net migration,..,-135020,..,..,..,..,-106360,..
272,Nicaragua,"Personal remittances, received (current US$)",913600000,1016300000,1081300000,1140200000,1197500000,1268100000,1394700000,1504800000
273,Nicaragua,"Foreign direct investment, net inflows (BoP, c...",936300000,767700000,815500000,884100000,949900000,898700000,771900000,359200000
274,Nicaragua,Net official development assistance and offici...,536580017.089844,532320007.324219,495799987.792969,432170013.427734,457920013.427734,430980010.986328,562590026.855469,351950012.207031

In [154]:
rds_connection_string = "admin1:12345@localhost:5432/ETL_Gary_and_Maria"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [155]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) FATAL:  database "ETL_Gary_and_Maria" does not exist

(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [153]:
new_customer_data_df.to_sql(name='customer_name', con=engine, if_exists='append', index=False)

NameError: name 'new_customer_data_df' is not defined